---
title: "Unit 3 Framingham Heart Study"
author: "Vinyas"
date: "9 May 2016"
output: html_document
---
#####Reading the data
```{r read}
framingham = read.csv("Data Files/framingham.csv")

# Look at structure
str(framingham)

# Load the library caTools
library(caTools)
```

#####Randomly split the data into training and testing sets
```{r split}
set.seed(1000)
split = sample.split(framingham$TenYearCHD, SplitRatio = 0.65)

# Split up the data using subset
train = subset(framingham, split==TRUE)
test = subset(framingham, split==FALSE)
```

#####Making a Logistic Regression model
```{r model}

framinghamLog = glm(TenYearCHD ~ ., data = train, family=binomial)
summary(framinghamLog)

# Predictions on the test set
predictTest = predict(framinghamLog, type="response", newdata=test)

```

#####Confusion matric and accuracy levels
```{r confusion }
table(test$TenYearCHD, predictTest > 0.5)

# Accuracy
(1069+11)/(1069+6+187+11)

# Baseline accuracy
(1069+6)/(1069+6+187+11)
```

#####Testing set AUC
```{r auc}
library(ROCR)
ROCRpred = prediction(predictTest, test$TenYearCHD)
as.numeric(performance(ROCRpred, "auc")@y.values)
```

#####Specificity and Selectivity
```{r tpr}
#Selectivity
11/(187+11)

#Specificity
1069/(1069+6)
```